In [1]:
import pandas as pd

### Đọc CSV file vào dataframe hoặc tạo dataframe

In [2]:
PATH = 'https://raw.githubusercontent.com/rmpbastos/data_sets/main/kaggle_housing/house_df.csv'
df = pd.read_csv(PATH)

In [9]:
#Tạo data frame
#df = pd.DataFrame(...)

In [3]:
df.head()

Id  LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  \
0   1     8450   Pave      CollgCr     2Story       2003          Y   
1   2     9600   Pave      Veenker     1Story       1976          Y   
2   3    11250   Pave      CollgCr     2Story       2001          Y   
3   4     9550   Pave      Crawfor     2Story       1915          Y   
4   5    14260   Pave      NoRidge     2Story       2000          Y   

   BedroomAbvGr  Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea  \
0             3           0     Attchd       2003.0         548         0   
1             3           1     Attchd       1976.0         460         0   
2             3           1     Attchd       2001.0         608         0   
3             3           1     Detchd       1998.0         642         0   
4             4           1     Attchd       2000.0         836         0   

  PoolQC Fence  SalePrice  
0    NaN   NaN     208500  
1    NaN   NaN     181500  
2    NaN   NaN     223500  
3    NaN   NaN     140000  
4    NaN   NaN     250000

dimension của df

In [4]:
df.shape

(1460, 16)

Overvew của data sử dụng hàm `info`<br>
Hàm này show một số thông tin về: 
- Lượng mem sử dụng
- Có bao nhiêu value non-null trong mỗi cột
- Type của từng cột

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Id            1460 non-null   int64  
 1   LotArea       1460 non-null   int64  
 2   Street        1460 non-null   object 
 3   Neighborhood  1460 non-null   object 
 4   HouseStyle    1460 non-null   object 
 5   YearBuilt     1460 non-null   int64  
 6   CentralAir    1460 non-null   object 
 7   BedroomAbvGr  1460 non-null   int64  
 8   Fireplaces    1460 non-null   int64  
 9   GarageType    1379 non-null   object 
 10  GarageYrBlt   1379 non-null   float64
 11  GarageArea    1460 non-null   int64  
 12  PoolArea      1460 non-null   int64  
 13  PoolQC        7 non-null      object 
 14  Fence         281 non-null    object 
 15  SalePrice     1460 non-null   int64  
dtypes: float64(1), int64(8), object(7)
memory usage: 182.6+ KB


Có thể sử dụng `describe` để xem analysis giá trị của từng cột. Hàm này chỉ show giá trị của các cột có dạng số (int, float)

- count - The number of not-empty values.
- mean - The average (mean) value.
- std - The standard deviation.
- min - the minimum value.
- 25% - The 25% percentile*.
- 50% - The 50% percentile*.
- 75% - The 75% percentile*.
- max - the maximum value.

* Percentiles are used in statistics to give you a number that describes the value that a given percent of the values are lower than.

Example: Let's say we have an array of the ages of all the people that lives in a street.

`ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]`

What is the 75. percentile? The answer is 43, meaning that 75% of the people are 43 or younger.

In [6]:
df.describe()

Id        LotArea    YearBuilt  BedroomAbvGr   Fireplaces  \
count  1460.000000    1460.000000  1460.000000   1460.000000  1460.000000   
mean    730.500000   10516.828082  1971.267808      2.866438     0.613014   
std     421.610009    9981.264932    30.202904      0.815778     0.644666   
min       1.000000    1300.000000  1872.000000      0.000000     0.000000   
25%     365.750000    7553.500000  1954.000000      2.000000     0.000000   
50%     730.500000    9478.500000  1973.000000      3.000000     1.000000   
75%    1095.250000   11601.500000  2000.000000      3.000000     1.000000   
max    1460.000000  215245.000000  2010.000000      8.000000     3.000000   

       GarageYrBlt   GarageArea     PoolArea      SalePrice  
count  1379.000000  1460.000000  1460.000000    1460.000000  
mean   1978.506164   472.980137     2.758904  180921.195890  
std      24.689725   213.804841    40.177307   79442.502883  
min    1900.000000     0.000000     0.000000   34900.000000  
25%    1961.000000   334.500000     0.000000  129975.000000  
50%    1980.000000   480.000000     0.000000  163000.000000  
75%    2002.000000   576.000000     0.000000  214000.000000  
max    2010.000000  1418.000000   738.000000  755000.000000

Ngoài ra có một số hàm show số unique data ở từng cột, ví dụ muốn xem unique value count của cột `GarageType`

In [8]:
df['GarageType'].value_counts()

Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

### Xử lý data trong pandas

Kiểm tra số unique values của cột `Id`

In [10]:
df['Id'].nunique()

1460

In [11]:
df.shape

(1460, 16)

Số lượng dòng bằng số unique values của `Id`, nên có thể set `Id` thành index thay vì index default của pandas

In [12]:
df.set_index('Id', inplace=True)

In [13]:
df.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460],
           dtype='int64', name='Id', length=1460)

`inplace=True` sẽ được dùng khi muốn thay đổi giá trị của chính df đang sử dụng. Nếu set bằng `False` thì hàm đó sẽ return về một bản copy đã được chỉnh sửa của df

Renaming columns<br>
Sử dụng dictionary để truyền tên cũ và mới vào, có thể đổi nhiều tên cùng 1 lúc

In [14]:
df.rename(columns={'BedroomAbvGr': 'Bedroom'}, inplace=True)

#### Thêm cột
Thêm cột ở pandas thì chỉ cần gán giá trị cho cột với tên tương ứng.<br>
Nếu gán bằng 1 value thì cả cột đó sẽ có value giống nhau, nếu gán bằng một list thì phải đảm bảo list đó cùng size với df đang muốn thêm cột

Trước tiên cần clone một df khác để thử chức năng thêm cột

In [15]:
df_copy = df.copy()

In [20]:
df_copy['Sold'] = "N"

In [18]:
df_copy.head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                          
1      8450   Pave      CollgCr     2Story       2003          Y        3   
2      9600   Pave      Veenker     1Story       1976          Y        3   
3     11250   Pave      CollgCr     2Story       2001          Y        3   
4      9550   Pave      Crawfor     2Story       1915          Y        3   
5     14260   Pave      NoRidge     2Story       2000          Y        4   

    Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC Fence  \
Id                                                                          
1            0     Attchd       2003.0         548         0    NaN   NaN   
2            1     Attchd       1976.0         460         0    NaN   NaN   
3            1     Attchd       2001.0         608         0    NaN   NaN   
4            1     Detchd       1998.0         642         0    NaN   NaN   
5            1     Attchd       2000.0         836         0    NaN   NaN   

    SalePrice Sold  
Id                  
1      208500    N  
2      181500    N  
3      223500    N  
4      140000    N  
5      250000    N

In [21]:
df_copy['Sold'] = [1,2,4]

ValueError: Length of values (3) does not match length of index (1460)

#### Thêm dòng
Giả sử mình muốn thêm một df khác vào df hiện có

In [24]:
data_to_append = {'LotArea': [9500, 15000],
                  'Bedroom': [5, 4],
                  'Fireplaces': [1, 0],
                  'GarageType': ['Attchd', 'Attchd'],
                  'GarageYrBlt': [2021, 2019],
                  'GarageArea': [300, 250],
                  'Steet': ['Pave', 'Gravel'],
                  'Neighborhood': ['Downtown', 'Downtown'],
                  'HouseStyle': ['2Story', '1Story'],
                  'YearBuilt': [2021, 2019],
                  'CentralAir': ['Y', 'N'],
                  'PoolArea': [0, 0],
                  'PoolQC': ['G', 'G'],
                  'Fence': ['G', 'G'],
                  'SalePrice': [250000, 195000],
                  'Sold': ['Y', 'Y']}

df_to_append = pd.DataFrame(data_to_append)

In [25]:
df_to_append.head()

LotArea  Bedroom  Fireplaces GarageType  GarageYrBlt  GarageArea   Steet  \
0     9500        5           1     Attchd         2021         300    Pave   
1    15000        4           0     Attchd         2019         250  Gravel   

  Neighborhood HouseStyle  YearBuilt CentralAir  PoolArea PoolQC Fence  \
0     Downtown     2Story       2021          Y         0      G     G   
1     Downtown     1Story       2019          N         0      G     G   

   SalePrice Sold  
0     250000    Y  
1     195000    Y

Thêm data vào cuối df cũ bằng hàm `append`

In [26]:
df_copy = df_copy.append(df_to_append, ignore_index=True)

/var/folders/0l/dvl_p7qs4yx7y2v7plhbhd800000gn/T/ipykernel_12823/2376635553.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_copy = df_copy.append(df_to_append, ignore_index=True)


In [27]:
df_copy.tail()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
1457     9042   Pave      Crawfor     2Story       1941          Y        4   
1458     9717   Pave        NAmes     1Story       1950          Y        2   
1459     9937   Pave      Edwards     1Story       1965          Y        3   
1460     9500    NaN     Downtown     2Story       2021          Y        5   
1461    15000    NaN     Downtown     1Story       2019          N        4   

      Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC  Fence  \
1457           2     Attchd       1941.0         252         0    NaN  GdPrv   
1458           0     Attchd       1950.0         240         0    NaN    NaN   
1459           0     Attchd       1965.0         276         0    NaN    NaN   
1460           1     Attchd       2021.0         300         0      G      G   
1461           0     Attchd       2019.0         250         0      G      G   

      SalePrice Sold   Steet  
1457     266500    N     NaN  
1458     142125    N     NaN  
1459     147500    N     NaN  
1460     250000    Y    Pave  
1461     195000    Y  Gravel

Có thể thấy thứ tự df mới cần append không giống df cũ, tuy nhiên vẫn có thể append được vì hàm này mapping tên cột với nhau<br>
Nếu có warning thì nên lên đọc phần docs để sửa lại cho phù hợp

In [28]:
df_copy = pd.concat([df_copy, df_to_append], ignore_index=True)

In [29]:
df_copy.tail()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
1459     9937   Pave      Edwards     1Story       1965          Y        3   
1460     9500    NaN     Downtown     2Story       2021          Y        5   
1461    15000    NaN     Downtown     1Story       2019          N        4   
1462     9500    NaN     Downtown     2Story       2021          Y        5   
1463    15000    NaN     Downtown     1Story       2019          N        4   

      Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC Fence  \
1459           0     Attchd       1965.0         276         0    NaN   NaN   
1460           1     Attchd       2021.0         300         0      G     G   
1461           0     Attchd       2019.0         250         0      G     G   
1462           1     Attchd       2021.0         300         0      G     G   
1463           0     Attchd       2019.0         250         0      G     G   

      SalePrice Sold   Steet  
1459     147500    N     NaN  
1460     250000    Y    Pave  
1461     195000    Y  Gravel  
1462     250000    Y    Pave  
1463     195000    Y  Gravel

#### Xóa cột hoặc xóa dòng

Xóa 2 dòng thừa lúc nãy add vào.<br>
`axis` 0 là default, tức delete row. 1 là column

In [30]:
df_copy.drop(labels=[1462, 1463], axis=0, inplace=True)

In [31]:
df_copy.tail()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
1457     9042   Pave      Crawfor     2Story       1941          Y        4   
1458     9717   Pave        NAmes     1Story       1950          Y        2   
1459     9937   Pave      Edwards     1Story       1965          Y        3   
1460     9500    NaN     Downtown     2Story       2021          Y        5   
1461    15000    NaN     Downtown     1Story       2019          N        4   

      Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC  Fence  \
1457           2     Attchd       1941.0         252         0    NaN  GdPrv   
1458           0     Attchd       1950.0         240         0    NaN    NaN   
1459           0     Attchd       1965.0         276         0    NaN    NaN   
1460           1     Attchd       2021.0         300         0      G      G   
1461           0     Attchd       2019.0         250         0      G      G   

      SalePrice Sold   Steet  
1457     266500    N     NaN  
1458     142125    N     NaN  
1459     147500    N     NaN  
1460     250000    Y    Pave  
1461     195000    Y  Gravel

Xóa cột tên `Fence`

In [32]:
df_copy.drop(labels='Fence', axis=1, inplace=True)

#### Filter giá trị trong bảng bằng `loc` và `iloc`
`loc` thường được dùng để filter với nhiều option hơn<br>
`iloc` thường được dùng khi biết index interger của row và column

##### 1. `iloc`
Select dựa vào vị trí của dòng

In [40]:
# Single selections using iloc and DataFrame
# Rows:
df.iloc[0] # first row
df.iloc[1] # second row
df.iloc[-1] # last row

LotArea            9937
Street             Pave
Neighborhood    Edwards
HouseStyle       1Story
YearBuilt          1965
CentralAir            Y
Bedroom               3
Fireplaces            0
GarageType       Attchd
GarageYrBlt      1965.0
GarageArea          276
PoolArea              0
PoolQC              NaN
Fence               NaN
SalePrice        147500
Name: 1460, dtype: object

Select dựa vào vị trí của cột

In [ ]:

# Columns:
df.iloc[:,0] # first column
df.iloc[:,1] # second column
df.iloc[:,-1] # last column

Select theo 1 range hoặc 1 list index

In [ ]:
# Multiple row and column selections using iloc and DataFrame
df.iloc[0:5] # first five rows
df.iloc[:, 0:2] # first two columns
df.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns.
df.iloc[0:5, 5:8] # first 5 rows and 5th, 6th, 7th columns

##### 2. `loc`
Truy xuất row dựa vào index, lưu ý 1000 là index chứ không phải row thứ 1000

In [41]:
df.loc[1000]

LotArea            6762
Street             Pave
Neighborhood    CollgCr
HouseStyle       1Story
YearBuilt          2006
CentralAir            Y
Bedroom               2
Fireplaces            0
GarageType       Attchd
GarageYrBlt      2006.0
GarageArea          632
PoolArea              0
PoolQC              NaN
Fence               NaN
SalePrice        206000
Name: 1000, dtype: object

In [34]:
df.loc[1000, ['LotArea', 'SalePrice']]


LotArea        6762
SalePrice    206000
Name: 1000, dtype: object

Select dựa vào list boolean

In [35]:
df.loc[df['SalePrice'] >= 700000]

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                            
692     21535   Pave      NoRidge     2Story       1994          Y        4   
1183    15623   Pave      NoRidge     2Story       1996          Y        4   

      Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC  Fence  \
Id                                                                             
692            2     Attchd       1994.0         832         0    NaN    NaN   
1183           2     Attchd       1996.0         813       555     Ex  MnPrv   

      SalePrice  
Id               
692      755000  
1183     745000

In [37]:
df.loc[[692, 1183]]

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                            
692     21535   Pave      NoRidge     2Story       1994          Y        4   
1183    15623   Pave      NoRidge     2Story       1996          Y        4   

      Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC  Fence  \
Id                                                                             
692            2     Attchd       1994.0         832         0    NaN    NaN   
1183           2     Attchd       1996.0         813       555     Ex  MnPrv   

      SalePrice  
Id               
692      755000  
1183     745000

Select columns và row

In [38]:
df.loc[[692, 1183], ["GarageArea", "SalePrice"]]

GarageArea  SalePrice
Id                         
692          832     755000
1183         813     745000

Select khoảng columns và khoảng rows

In [39]:
df.loc[697:700, "GarageArea":"SalePrice"]

GarageArea  PoolArea PoolQC  Fence  SalePrice
Id                                                
697         205         0    NaN    NaN      89000
698         308         0    NaN    NaN     123500
699         336         0    NaN  MnPrv     138500
700         530         0    NaN    NaN     196000

Chọn những rows có Street bằng Pave, các cột từ LotArea đến Bedroom

In [42]:
df.loc[df['Street'] == 'Pave', 'LotArea':'Bedroom'].head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom
Id                                                                       
1      8450   Pave      CollgCr     2Story       2003          Y        3
2      9600   Pave      Veenker     1Story       1976          Y        3
3     11250   Pave      CollgCr     2Story       2001          Y        3
4      9550   Pave      Crawfor     2Story       1915          Y        3
5     14260   Pave      NoRidge     2Story       2000          Y        4

Chọn những dòng có Neighborhood bắt đầu bằng Coll

In [43]:
df.loc[df['Neighborhood'].str.startswith("Coll")].head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                          
1      8450   Pave      CollgCr     2Story       2003          Y        3   
3     11250   Pave      CollgCr     2Story       2001          Y        3   
14    10652   Pave      CollgCr     1Story       2006          Y        3   
23     9742   Pave      CollgCr     1Story       2002          Y        3   
33    11049   Pave      CollgCr     1Story       2007          Y        3   

    Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC Fence  \
Id                                                                          
1            0     Attchd       2003.0         548         0    NaN   NaN   
3            1     Attchd       2001.0         608         0    NaN   NaN   
14           1     Attchd       2006.0         840         0    NaN   NaN   
23           1     Attchd       2002.0         534         0    NaN   NaN   
33           0     Attchd       2007.0         484         0    NaN   NaN   

    SalePrice  
Id             
1      208500  
3      223500  
14     279500  
23     230000  
33     179900

Chọn những dòng năm xây dựng YearBuilt trong những năm 2006 và 2007

In [44]:
df.loc[df['YearBuilt'].isin([2006, 2007])].head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                          
14    10652   Pave      CollgCr     1Story       2006          Y        3   
26    14230   Pave      NridgHt     1Story       2007          Y        3   
28    11478   Pave      NridgHt     1Story       2007          Y        3   
33    11049   Pave      CollgCr     1Story       2007          Y        3   
48    11096   Pave      Somerst     1Story       2006          Y        3   

    Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC Fence  \
Id                                                                          
14           1     Attchd       2006.0         840         0    NaN   NaN   
26           1     Attchd       2007.0         890         0    NaN   NaN   
28           1     Attchd       2008.0         772         0    NaN   NaN   
33           0     Attchd       2007.0         484         0    NaN   NaN   
48           0     Attchd       2006.0         826         0    NaN   NaN   

    SalePrice  
Id             
14     279500  
26     256300  
28     306000  
33     179900  
48     249700

Chọn những dòng Neighborhood bắt đầu bởi Coll và năm xây dựng khoảng 2006 2007

In [46]:
df.loc[df['Neighborhood'].str.startswith("Coll") & df['YearBuilt'].isin([2006, 2007])].head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                           
14     10652   Pave      CollgCr     1Story       2006          Y        3   
33     11049   Pave      CollgCr     1Story       2007          Y        3   
113     9965   Pave      CollgCr     2Story       2007          Y        4   
221     8990   Pave      CollgCr     1Story       2006          Y        2   
258     8814   Pave      CollgCr     1Story       2006          Y        3   

     Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC Fence  \
Id                                                                           
14            1     Attchd       2006.0         840         0    NaN   NaN   
33            0     Attchd       2007.0         484         0    NaN   NaN   
113           1    BuiltIn       2007.0         792         0    NaN   NaN   
221           0     Attchd       2006.0         675         0    NaN   NaN   
258           1     Attchd       2006.0         660         0    NaN   NaN   

     SalePrice  
Id              
14      279500  
33      179900  
113     383970  
221     204900  
258     220000

Chọn những dòng có năm xây dựng sau 2000 và trước 2005, show những cột 'LotArea', 'Bedroom', 'GarageType'

In [47]:
df.loc[(df['YearBuilt'] > 2000) & (df['YearBuilt'] <= 2005), ['LotArea', 'Bedroom', 'GarageType']].head()

LotArea  Bedroom GarageType
Id                             
1      8450        3     Attchd
3     11250        3     Attchd
7     10084        3     Attchd
12    11924        4    BuiltIn
19    13695        3     Detchd

lambda function trả về giá trị True hoặc False<br>
Chọn những nhà có HouseStyle có ký tự đầu là 2

In [49]:
df.loc[df['HouseStyle'].apply(lambda s: s[0] == '2')].head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
Id                                                                          
1      8450   Pave      CollgCr     2Story       2003          Y        3   
3     11250   Pave      CollgCr     2Story       2001          Y        3   
4      9550   Pave      Crawfor     2Story       1915          Y        3   
5     14260   Pave      NoRidge     2Story       2000          Y        4   
8     10382   Pave       NWAmes     2Story       1973          Y        3   

    Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC Fence  \
Id                                                                          
1            0     Attchd       2003.0         548         0    NaN   NaN   
3            1     Attchd       2001.0         608         0    NaN   NaN   
4            1     Detchd       1998.0         642         0    NaN   NaN   
5            1     Attchd       2000.0         836         0    NaN   NaN   
8            2     Attchd       1973.0         484         0    NaN   NaN   

    SalePrice  
Id             
1      208500  
3      223500  
4      140000  
5      250000  
8      200000

Có thể tạo một list idx ở ngoài `loc`

In [50]:
idx = df['HouseStyle'].apply(lambda s: s[0] == '2')
# Sau đó chọn những dòng thỏa mãn điều kiện của idx
df.loc[idx, ['LotArea', 'Street', 'HouseStyle', 'YearBuilt']].head()

LotArea Street HouseStyle  YearBuilt
Id                                      
1      8450   Pave     2Story       2003
3     11250   Pave     2Story       2001
4      9550   Pave     2Story       1915
5     14260   Pave     2Story       2000
8     10382   Pave     2Story       1973

##### Ngoài ra có thể gán giá trị cho các dòng bằng `loc`

In [56]:
# Đổi HouseStyle thành 9Story với những nhà xây sau năm 2000
df_copy.loc[df_copy['YearBuilt'] > 2000, "HouseStyle"] = "9Story"

In [57]:
df_copy.loc[df_copy['YearBuilt'] > 2000].head()

LotArea Street Neighborhood HouseStyle  YearBuilt CentralAir  Bedroom  \
0      8450   Pave      CollgCr     9Story       2003          Y        3   
2     11250   Pave      CollgCr     9Story       2001          Y        3   
6     10084   Pave      Somerst     9Story       2004          Y        3   
11    11924   Pave      NridgHt     9Story       2005          Y        4   
13    10652   Pave      CollgCr     9Story       2006          Y        3   

    Fireplaces GarageType  GarageYrBlt  GarageArea  PoolArea PoolQC  \
0            0     Attchd       2003.0         548         0    NaN   
2            1     Attchd       2001.0         608         0    NaN   
6            1     Attchd       2004.0         636         0    NaN   
11           2    BuiltIn       2005.0         736         0    NaN   
13           1     Attchd       2006.0         840         0    NaN   

    SalePrice Sold Steet  
0      208500    N   NaN  
2      223500    N   NaN  
6      307000    N   NaN  
11     345000    N   NaN  
13     279500    N   NaN

## Numpy

In [3]:
import numpy as np

Python variable contains more than just their value. Because it is dynamic type

In [1]:
x = 4
x = "bốn"

A python object (interger, float, ...) contains variable type, size, value, ...<br>
Python list is a dynamic type python list. It contains a pointer that points to a block of pointers which in turn, each pointer points to a python object<br>
Numpy array is like a C array which contains a single pointer which points to a block of data

In [6]:
L = range(1000)
%timeit [i**2 for i in L]

207 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
a = np.arange(1000)
%timeit a**2

551 ns ± 1.49 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Creating arrays

In [10]:
# 1-d array
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [11]:
# 2-d array
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

Functions for creating arrays

Evenly spaced

In [12]:
a = np.arange(10) # 0 .. n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(1, 8, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

by number of points

In [22]:
c = np.linspace(0, 2, 5)   # start, end, num-points
c

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
d = np.linspace(0, 1.5, 5, endpoint=False) # include final step or not
d

array([0. , 0.3, 0.6, 0.9, 1.2])

Common arrays

In [23]:
a = np.ones((2, 2))  # reminder: (2, 2) is a tuple
a

array([[1., 1.],
       [1., 1.]])

In [24]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [25]:
c = np.eye(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Indexing and slicing

In [45]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sliding [start:stop:step]

In [46]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
a[1::-1]

array([1, 0])

Multi dimensional

In [48]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [49]:
a[1, 1]

1

In [51]:
a[2, 1] = 10
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [52]:
a[1]

array([0, 1, 0])

In [53]:
a[1:3]

array([[ 0,  1,  0],
       [ 0, 10,  2]])